# Generated by Django 5.2.6 on 2025-11-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=20),
        ),
    ]
