# Generated by Django 5.2.6 on 2025-11-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='date_of_completion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
