# Generated by Django 5.2.6 on 2025-11-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectrequest_date_of_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrequest',
            name='date_of_completion',
        ),
    ]
