# Generated by Django 5.2.6 on 2025-11-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projectrequest_date_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='date_of_completion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
