# Generated by Django 5.2.6 on 2025-11-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_remove_projectupdates_image_projectupdateimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdates',
            name='read_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectupdates',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
