# Generated by Django 5.2.6 on 2025-11-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_projectupdates_read_by_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdates',
            name='date_of_completion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
