# Generated by Django 5.2.6 on 2025-11-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_projectupdates_date_of_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdates',
            name='date_of_completion',
        ),
    ]
