# Generated by Django 5.2.6 on 2025-12-02 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectrequest_artisan'),
        ('updates', '0005_remove_projectupdates_date_of_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdates',
            name='artisan',
        ),
        migrations.RemoveField(
            model_name='projectupdates',
            name='project',
        ),
        migrations.CreateModel(
            name='ProjectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('chat', 'Chat Message'), ('milestone', 'Milestone Update')], default='chat', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_by_client', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.projectrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_messages/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='updates.projectmessage')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectUpdateImage',
        ),
        migrations.DeleteModel(
            name='ProjectUpdates',
        ),
    ]
