# Generated by Django 5.2.6 on 2025-12-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_remove_projectupdates_artisan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
