# Generated by Django 5.2.6 on 2025-12-04 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0007_projectmessage_flagged_projectmessage_reviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='review_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
