# Generated by Django 5.2.6 on 2025-12-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0008_projectmessage_review_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmessage',
            old_name='reviewed',
            new_name='blocked',
        ),
        migrations.RemoveField(
            model_name='projectmessage',
            name='review_message',
        ),
        migrations.RemoveField(
            model_name='projectmessage',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='reviewed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
