# Generated by Django 5.2.6 on 2025-12-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0009_rename_reviewed_projectmessage_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='read_by_artisan',
            field=models.BooleanField(default=False),
        ),
    ]
