# Generated by Django 5.2.6 on 2026-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisanapplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanapplication',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='artisanapplication',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
