# Generated by Django 5.2.6 on 2025-11-13 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_projectrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposed_timeline', models.CharField(blank=True, help_text='Expected completion time or duration', max_length=255, null=True)),
                ('proposed_timeline_date', models.DateField(blank=True, help_text='Temporary field to store converted date', null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes or details from the artisan', null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(limit_choices_to={'role': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.projectrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'artisan')},
            },
        ),
    ]
