# Generated by Django 5.2.6 on 2025-11-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='proposed_timeline',
        ),
    ]
