# Generated by Django 5.2.6 on 2025-11-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_remove_proposal_proposed_timeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='proposed_timeline_date',
            new_name='proposed_date_of_completion',
        ),
    ]
