# Generated by Django 5.2.6 on 2025-11-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_rename_proposed_timeline_date_proposal_proposed_date_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='negotiated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
