# Generated by Django 5.2.6 on 2025-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rating_images/'),
        ),
    ]
