# Generated by Django 5.2.6 on 2026-05-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisanmatching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('proposed', 'Proposed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
