# Generated by Django 5.2.6 on 2026-05-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisanmatching', '0002_artisanmatch_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanmatch',
            name='status',
        ),
    ]
