# Generated by Django 5.2.6 on 2025-11-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='has_unread_artisan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='has_unread_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='last_message_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='negotiationmessage',
            name='read_by_artisan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negotiationmessage',
            name='read_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
