# Generated by Django 5.2.6 on 2025-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0002_negotiation_has_unread_artisan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='pending_final_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
