# Generated by Django 5.2.6 on 2025-11-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0003_negotiation_pending_final_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negotiation',
            old_name='pending_final_offer',
            new_name='pending_final_amount',
        ),
    ]
