# Generated by Django 5.2.6 on 2025-12-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0004_rename_pending_final_offer_negotiation_pending_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationmessage',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negotiationmessage',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
