# Generated by Django 5.2.6 on 2025-11-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('artisan', 'Artisan'), ('buyer', 'Buyer'), ('admin', 'Admin')], default='buyer', max_length=10),
        ),
    ]
