# Generated by Django 5.2.6 on 2025-11-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('artisan', 'Artisan'), ('client', 'Client'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
