# Generated by Django 5.2.6 on 2025-11-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_artisanprofile_user_alter_clientprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
