# Generated by Django 5.2.6 on 2025-11-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_artisanprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('artisan', 'Artisan'), ('admin', 'Admin')], default='artisan', max_length=10),
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
