# Generated by Django 5.2.6 on 2025-11-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_portfolioitem_image_portfolioimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='artisan',
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.DeleteModel(
            name='ArtisanProfile',
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
