# Generated by Django 5.2.6 on 2026-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_paid_ready_products',
            field=models.BooleanField(default=False),
        ),
    ]
