# Generated by Django 5.2.6 on 2026-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_artisanprofile_created_at_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='completed_projects',
            field=models.IntegerField(default=0),
        ),
    ]
